---
# tasks file for role_test1

- name: foobar
  debug:
    msg: Hello world

- name: return motd to registered var
  command: cat /etc/motd  # noqa 301
  register: mymotd
- name: edit inputrc
  sudo: true # noqa 103
  lineinfile:
    path: /etc/inputrc
    state: present
    line: '# added via ansible'
- name: application service
  docker:  # noqa 105
    name: myservice
    image: someuser/serviceimage
    state: restarted
- name: Copy local file to remote
  copy:
    src: vars.yml
    dest: "{{ dest_proj_path }}/config/ansible/vars.yml"
# - name: Create firewalld config directories
#   file:
#     dest: "{{ item }}"
#     state: directory
#     mode: 750
#   with_items:
#     - /etc/firewalld
#     - /etc/firewalld/zones
  notify: firewalld__reload
- name: octal permissions test success (0777)
  file: path=baz mode=777
- shell:
    cmd: echo
    environment: '{{ foo }}'
